version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TrafficGuard"
s3_bucket = "traffic-guard-lambda"
s3_prefix = "TrafficGuard"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
