version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TrafficGuardPlatesRecognizer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ggn4cqjnvdza"
s3_prefix = "TrafficGuardPlatesRecognizer"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SourceImagesBucketName=\"traffic-guard-frames\" TargetImagesBucketName=\"traffic-guard-cars-and-plates\" TrafficGuardParsedCarLicensePlatesTableName=\"TrafficGuardParsedCarLicensePlates\" CreateTable=\"true\" RemoveProcessedImagesFromSourceBucket=\"false\" SaveAlreadyRecognizedAgainInMinutes=\"5\" RekognitionServiceRegion=\"eu-central-1\""
profile = "default"
